@echo off
TITLE Sovereign Desktop Orchestrator
echo [SOVEREIGN] Starting Multi-Screen Desktop App...
cd desktop-app
echo [SOVEREIGN] Checking dependencies...
if not exist node_modules (
    echo [SOVEREIGN] Installing dependencies (first time only)...
    call npm install
)
echo [SOVEREIGN] Launching Electron...
npm start
pause
